services:
  - type: web
    name: inventory-app-prod
    env: python
    buildCommand: |
      pip install -r requirements.txt
    preDeployCommand: flask db upgrade
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 120 app:app
    healthCheckPath: /healthz
    envVars:
      - key: FLASK_APP
        value: app.py
