services:
  - type: web
    name: inventory-app-prod
    env: python
    buildCommand: |
      pip install -r requirements.txt
    preDeployCommand: flask db upgrade
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_APP
        value: app.py
