"""Add cashier_id to Sale

Revision ID: 0295071a0e38
Revises: 905795dc2ba0
Create Date: 2025-09-20 15:31:22.563412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0295071a0e38'
down_revision = '905795dc2ba0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cashier_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_sale_cashier_id_user_id', 'user', ['cashier_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sale_cashier_id_user_id', type_='foreignkey')
        batch_op.drop_column('cashier_id')

    # ### end Alembic commands ###
