"""add unit_price to sale

Revision ID: 905795dc2ba0
Revises: 
Create Date: 2025-06-17 10:28:28.372991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '905795dc2ba0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_column('unit_price')

    # ### end Alembic commands ###
